site_name: PyTry

theme:
  name: mkdocs
  navigation_depth: 3

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/pyodide_runner.js
