site_name: PyTry

nav:
  - Home: index.md
  - Basic Data Types: basic_data_types.md
  - Collections of Data: collections_of_data.md

theme:
  name: mkdocs
  navigation_depth: 3

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/pyodide_runner.js
